<a href="https://colab.research.google.com/github/IqbalPratama17/Machine-Learning/blob/Python/UAS_Moch_Iqbal_P_(2018102048).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Travel**

In [1]:
# Membuat Dataset
jk = ['laki-laki','laki-laki','Perempuan','Perempuan','laki-laki','laki-laki','Perempuan',
      'Perempuan','laki-laki','Perempuan']
biaya = ['Murah','Murah','Murah','Murah','Murah','Standar','Standar','Mahal','Mahal','Mahal']
income = ['Rendah','Sedang','Sedang','Rendah','Sedang','Sedang','Sedang','Tinggi','Sedang','Tinggi']
transpotasi = ['Bus','Bus','Kereta api','Bus','Bus','Kereta api','Kereta api','Mobil','Mobil','Mobil']
tujuan = ['No','Yes','Yes','No','Yes','No','Yes','Yes','No','No']

In [2]:
# Import Label Encoder
from sklearn import preprocessing

# Creating Label Encoder
lb = preprocessing.LabelEncoder()

# Convert label string to numbers
jk_encoded = lb.fit_transform(jk)
print (jk_encoded)

# Convert label string to numbers
biaya_encoded = lb.fit_transform(biaya)
print (biaya_encoded)

[1 1 0 0 1 1 0 0 1 0]
[1 1 1 1 1 2 2 0 0 0]


In [3]:
# Convert label string to numbers
income_encoded = lb.fit_transform(income)
print (income_encoded)

# Convert label string to numbers
transpotasi_encoded = lb.fit_transform(transpotasi)
print (transpotasi_encoded)

[0 1 1 0 1 1 1 2 1 2]
[0 0 1 0 0 1 1 2 2 2]


In [4]:
label=lb.fit_transform(tujuan)
print ("jk          :", jk_encoded)
print ("biaya       :", biaya_encoded)
print ("income      :", income_encoded)
print ("transpotasi :", transpotasi_encoded)
print ("tujuan      :", label)

jk          : [1 1 0 0 1 1 0 0 1 0]
biaya       : [1 1 1 1 1 2 2 0 0 0]
income      : [0 1 1 0 1 1 1 2 1 2]
transpotasi : [0 0 1 0 0 1 1 2 2 2]
tujuan      : [0 1 1 0 1 0 1 1 0 0]


In [5]:
# Combine fitur-fitur yang ada
features = zip(jk_encoded,biaya_encoded,income_encoded,transpotasi_encoded)
features = list(features)
print (tuple(features))

((1, 1, 0, 0), (1, 1, 1, 0), (0, 1, 1, 1), (0, 1, 0, 0), (1, 1, 1, 0), (1, 2, 1, 1), (0, 2, 1, 1), (0, 0, 2, 2), (1, 0, 1, 2), (0, 0, 2, 2))


In [6]:
# Import gaussain naive bayes model
from sklearn.naive_bayes import GaussianNB

# Panggil gaussain classifier
model = GaussianNB()

# Train Model untuk data training
model.fit(features,label)
# model.fit(features,label.reshape(-1,1))

# Predict Output
predicted= model.predict([[0,2,0,0]])
print ("Hasil Predict :", predicted)

Hasil Predict : [0]


**Kesimpulan**
1.   Jenis kelamin    = ”Perempuan”
2.   Biaya Perjalanan = ”Standar”
3.   Income level     = ”Rendah”
4.   Transportasi     = ”Bus”
5.   Tujuan           = ”No”